
import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
async function api(p,o={}){let h={"Content-Type":"application/json",...(o.headers||{})},t=localStorage.getItem("token");if(t)h.Authorization=`Bearer ${t}`;let r=await fetch(API+p,{...o,headers:h}),d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");return d}
function App(){const[user,setUser]=useState(null),[a,setA]=useState([]),[tx,setTx]=useState([]),[mode,setMode]=useState("login"),[f,setF]=useState({name:"",email:"",password:""}),[tr,setTr]=useState({amount:"",description:""}),[err,setErr]=useState("");
const load=async()=>{try{let d=await api("/dashboard");setUser(d.user);setA(d.accounts);if(d.accounts[0])setTx((await api("/transactions/"+d.accounts[0].id)).transactions)}catch{localStorage.clear();setUser(null)}};useEffect(()=>{if(localStorage.getItem("token"))load()},[]);
const auth=async e=>{e.preventDefault();try{let d=await api(mode==="login"?"/login":"/register",{method:"POST",body:JSON.stringify(f)});localStorage.setItem("token",d.token);await load()}catch(e){setErr(e.message)}};
const send=async e=>{e.preventDefault();try{await api("/transfer",{method:"POST",body:JSON.stringify({account_id:a[0].id,...tr})});setTr({amount:"",description:""});await load()}catch(e){setErr(e.message)}};
if(!user)return <main className="auth"><form className="card authcard" onSubmit={auth}><div className="brand">NEXUS<span>BANK</span></div><h1>{mode==="login"?"Welcome back":"Create account"}</h1>{mode==="register"&&<input placeholder="Full name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/>}<input type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input type="password" placeholder="Password (8+ chars)" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{err&&<p className="error">{err}</p>}<button>{mode==="login"?"Sign in":"Register"}</button><button type="button" className="link" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"Back to sign in"}</button></form></main>;
let x=a[0];return <><nav><div className="brand">NEXUS<span>BANK</span></div><div>Hi, {user.name} <button className="logout" onClick={()=>{localStorage.clear();setUser(null)}}>Logout</button></div></nav><section className="container"><h1>Financial Overview</h1><div className="grid"><div className="card balance"><p>Available balance</p><h2>₹{x?.balance.toLocaleString("en-IN",{minimumFractionDigits:2})}</h2><small>Account •••• {x?.account_number.slice(-4)}</small></div><div className="card"><p>Account type</p><h3>{x?.account_type}</h3><p>Active</p></div><div className="card"><p>Transactions</p><h3>{tx.length}</h3></div></div><div className="lower"><div className="card"><h2>Transfer</h2><form onSubmit={send}><input type="number" min="1" step=".01" placeholder="Amount" value={tr.amount} onChange={e=>setTr({...tr,amount:e.target.value})}/><input placeholder="Description" value={tr.description} onChange={e=>setTr({...tr,description:e.target.value})}/>{err&&<p className="error">{err}</p>}<button>Send money</button></form></div><div className="card"><h2>Recent transactions</h2>{tx.map(t=><div className="tx" key={t.id}><span><b>{t.description}</b><small>{new Date(t.created_at).toLocaleString()}</small></span><strong className={t.type==="DEBIT"?"debit":"credit"}>{t.type==="DEBIT"?"−":"+"}₹{t.amount.toFixed(2)}</strong></div>)}</div></div></section></>}
createRoot(document.getElementById("root")).render(<App/>);
